import { linkTodoistTask, normalizeTodoistTask } from '@/lib/todoist-deterministic-linking'

const base = () => ({ getConnection: jest.fn().mockResolvedValue({ id: 'c', userId: 'u', provider: 'todoist', providerAccountId: 'a' }), fetchTask: jest.fn().mockResolvedValue({ id: 't', is_completed: false }), ownsTarget: jest.fn().mockResolvedValue(true), findActive: jest.fn().mockResolvedValue(null), saveMapping: jest.fn().mockResolvedValue({ id: 'm' }), updateMapping: jest.fn() })
describe('Todoist deterministic linking', () => {
  it('normalizes deterministically', () => { const a = normalizeTodoistTask({ id: 't', is_completed: false }); const b = normalizeTodoistTask({ id: 't', is_completed: false }); expect(a.hash).toBe(b.hash) })
  it('verifies canonical task and persists baseline', async () => { const p = base(); const r = await linkTodoistTask({ userId: 'u', connectionId: 'c', taskId: 't', internalType: 'ChecklistItem', internalId: 'i' }, p); expect(r.idempotent).toBe(false); expect(p.saveMapping).toHaveBeenCalledWith(expect.objectContaining({ status: 'active', canonicalBaseline: expect.objectContaining({ hash: expect.any(String) }) })) })
  it('rejects unowned target and provider failure', async () => { const p = base(); p.ownsTarget.mockResolvedValue(false); await expect(linkTodoistTask({ userId: 'u', connectionId: 'c', taskId: 't', internalType: 'ChecklistItem', internalId: 'i' }, p)).rejects.toThrow('Target not owned'); const q = base(); q.fetchTask.mockResolvedValue(null); await expect(linkTodoistTask({ userId: 'u', connectionId: 'c', taskId: 't', internalType: 'ChecklistItem', internalId: 'i' }, q)).rejects.toThrow('unavailable') })
  it('makes identical link idempotent and detects conflicts', async () => { const p = base(); p.findActive.mockResolvedValue({ internalType: 'ChecklistItem', internalId: 'i' }); const r = await linkTodoistTask({ userId: 'u', connectionId: 'c', taskId: 't', internalType: 'ChecklistItem', internalId: 'i' }, p); expect(r.idempotent).toBe(true); const q = base(); q.findActive.mockResolvedValue({ internalType: 'ChecklistItem', internalId: 'other' }); await expect(linkTodoistTask({ userId: 'u', connectionId: 'c', taskId: 't', internalType: 'ChecklistItem', internalId: 'i' }, q)).rejects.toThrow('conflict') })
})
